### ISSUE TITLE
Slack link not opening

### ISSUE THREAD

**Issue by jahnvigupta** [moja-global/LEMP.Baseline_Algorithm#1]
**Describe the bug**
There is some issue with the Slack channel link given in readme. It shows page not found error on clicking.

**To Reproduce**
1. Go to README.nd.
2. Scroll down to FAQ and Other Questions.
3. Click on moja global's Slack workspace.

**Comment by ShubhamPandey28** [comment]
try [this](https://mojaglobal.slack.com) after receiving the invitation sent to you. I hope it helps.

**Comment by ShubhamPandey28** [comment]
@jahnvigupta try [this](https://mojaglobal.slack.com) after the invitation is sent to you. hope it helps

**Comment by jahnvigupta** [comment]
thanks @ShubhamPandey28

**Comment by Patamap** [comment]
@jahnvigupta is this solved? If yes, can you please close this issue, please?

**Comment by jahnvigupta** [comment]
sure @Patamap
